# Generated by Django 4.2.19 on 2025-04-01 12:46

from django.db import migrations, models
import lms.djangoapps.courseware.fields


class Migration(migrations.Migration):

    dependencies = [
        ('courseware', '0017_financialassistanceconfiguration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodule',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
